name: Sync to ModelScope

on:
  push:
    branches: [ main ]  # 如果你的主分支叫 master，请把这里改为 master

jobs:
  sync-to-modelscope:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to ModelScope
        run: |
          # 1. 配置 Git 用户信息（这是虚拟的，不用改）
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 2. 强制推送到你的魔搭仓库
          # 下面这一行我已经帮你改好了地址
          git push -f https://${{ secrets.MODELSCOPE_USERNAME }}:${{ secrets.MODELSCOPE_TOKEN }}@www.modelscope.cn/studios/lyshang9989/Analysis.git main
